// Create an object with keys generated by running the provided function for each key and the same values as the provided object
//#Source https://bit.ly/2neWfJ2
const mapKeys = (obj, fn) =>
  Object.keys(obj).reduce((acc, k) => {
    acc[fn(obj[k], k, obj)] = obj[k];
    return acc;
  }, {});

console.log(mapKeys({ a: 1, b: 2 }, (val, key) => key + val)); // {"a1":1,"b2":2}
