// Create an object with the same keys as the provided object and values generated by running the provided function for each value
//#Source https://bit.ly/2neWfJ2
const mapValues = (obj, fn) =>
  Object.keys(obj).reduce((acc, k) => {
    acc[k] = fn(obj[k], k, obj);
    return acc;
  }, {});
const users = {
  fred: { user: "fred", age: 40 },
  pebbles: { user: "pebbles", age: 1 },
};

console.log(mapValues(users, (u) => u.age)); // {"fred":40,"pebbles":1}
